sonar.organization=ozan
sonar.projectKey=ozanyildirim-hub_ozanC-demo
sonar.projectName=ozanC++demo
sonar.projectVersion=1.0.0

sonar.sources=src,include
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.cfamily.compile-commands=build/compile_commands.json
